### ISSUE TITLE
Clicking the open source club's logo should link to their website

### ISSUE THREAD

**Issue by okanji** [truopensource/git-intro#2]
<img width="236" alt="Screen Shot 2019-10-16 at 1 46 20 AM" src="https://user-images.githubusercontent.com/30703259/66903171-d483bb00-efb6-11e9-96d0-8b651dd5b7f8.png">

The open source clubs logo (second from the left) does not have a link attached to it. When clicked, it should link back to their website: https://ossn.club/clubs/21

**Comment by okanji** [comment]
This issue is for a tutorial, please do not make a PR if you are not part of the session.

**Comment by dipakparmar** [comment]
Solved in #8
